lang: "fr"

status:
  valid: "&a[Validé]"
  notValid: "&c[Non Validé]"

titles:
  item: "{Status} &a{Quantity} x &7{DisplayNameItem}"
  money: "{Status} &a{Quantity} suns"
  experience: "{Status} Expérience * {Quantity}"
  skills: "{Status} Skills {DisplayNameItem} {Quantity}"
  total_skills: "{Status} &a{Quantity} &7niveaux de compétence ( en tout )"
  company: "{Status} &7Appartenir ou avoir créé une entreprise de niveau &a4"
  diversity: "{Status} &7Note de diversité inférieur à &a{Quantity}"
  fish: "{Status} {DisplayNameItem} &7( > &a{Quantity} &7lbs)"
descriptions:
  item:
    - "&7Vous devez posséder &a{Quantity} {DisplayNameItem}."
  money:
    - "&7Vous devez posséder &a{Quantity} suns."
  experience:
    - "&7Vous devez posséder {Quantity} d'expérience."
  skills:
    - "&7Vous devez posséder {Quantity} de niveau dans le skills {DisplayNameItem}."
  total_skills:
    - "&7Vous devez posséder &a{Quantity} &7niveaux de compétence,"
    - "&7toutes compétences cumulées."
  company:
    - "&7Vous devez posséder ou être dans une entreprise de niveau &a4."
  diversity:
    - "&7Vôtre note de diversité doit être en dessous de &a{Quantity}."
  fish:
    - "&7Vous devez posséder un {DisplayNameItem}"
    - "&7dont le poids est supérieur à &a{Quantity}"
    - "&7Obtenable au warp custom !"
display:
  MONEY: "EMERALD"
  EXPERIENCE: "EXPERIENCE_BOTTLE"
  SKILLS: "DIAMOND_SWORD"
  TOTAL_SKILLS: "DIAMOND_SWORD"
  COMPANY: "END_PORTAL_FRAME"
  DIVERSITY: "END_CRYSTAL"

broadcast: "&3&lRankup &7» &6***Félicitations à &6&n{PlayerName}&6*** &aQui vient de passer {GradeName} &a!"