lang: "fr"

status:
  valid: "&a[Valider]"
  notValid: "&c[Non Valider]"

titles:
  item: "{Status} {DisplayNameItem} * {Quantity}"
  money: "{Status} Argent * {Quantity}"
  experience: "{Status} Expérience * {Quantity}"
  skills: "{Status} Skills {DisplayNameItem} {Quantity}"
  total_skills: "{Status} Skills {Quantity}"
descriptions:
  item:
    - "Vous devez possèder {Quantity} de {DisplayNameItem}."
  money:
    - "Vous devez possèder {Quantity} d'argent."
  experience:
    - "Vous devez possèder {Quantity} d'expérience."
  skills:
    - "Vous devez possèder {Quantity} de niveau dans le skills {DisplayNameItem}."
  total_skills:
    - "Vous devez possèder {Quantity} de niveau dans tous les skills."
display:
  MONEY: "GOLD_INGOT"
  EXPERIENCE: "EXPERIENCE_BOTTLE"
  SKILLS: "DIAMOND_SWORD"
  TOTAL_SKILLS: "DIAMOND_SWORD"

broadcast: "Le joueur {PlayerName} est monté au grade {GradeName}"